# Generated by Django 4.0.3 on 2024-03-12 05:52
"""
Class docstring: Brief description of the NotificationConsumer class.
"""
from django.db import migrations


class Migration(migrations.Migration):
    """
    Class docstring: Brief description of the NotificationConsumer class.
    """

    dependencies = [
        ('blog_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-published',), 'permissions': [('can_add_new_project', 'can add new project')]},
        ),
    ]
