# Generated by Django 4.0.3 on 2024-03-12 05:57
"""
Class docstring: Brief description of the NotificationConsumer class.
"""
from django.db import migrations


class Migration(migrations.Migration):
    """
    Class docstring: Brief description of the NotificationConsumer class.
    """

    dependencies = [
        ('blog_api', '0003_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-published',)},
        ),
    ]
