# Generated by Django 4.2.11 on 2024-03-13 06:29
"""
Class docstring: Brief description of the NotificationConsumer class.
"""
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Class docstring: Brief description of the NotificationConsumer class.
    """

    dependencies = [
        ('blog_api', '0007_alter_post_options_post_is_popular_post_is_trending'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
