# Generated by Django 4.2.11 on 2024-03-13 09:57
"""
Class docstring: Brief description of the NotificationConsumer class.
"""
from django.db import migrations, models


class Migration(migrations.Migration):
    """
Class docstring: Brief description of the NotificationConsumer class.
"""

    dependencies = [
        ('blog_api', '0009_post_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='last_visit',
            field=models.DateTimeField(default='2024-03-13 12:30:45'),
        ),
    ]
