# Generated by Django 4.2.11 on 2024-03-13 10:00
"""
Class docstring: Brief description of the NotificationConsumer class.
"""
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Class docstring: Brief description of the NotificationConsumer class.
    """

    dependencies = [
        ('blog_api', '0010_post_last_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='last_visit',
            field=models.DateTimeField(default='2024-03-13 03:00:45'),
        ),
    ]
