# Generated by Django 4.2.11 on 2024-03-13 10:10
"""
Class docstring: Brief description of the NotificationConsumer class.
"""
from django.db import migrations


class Migration(migrations.Migration):
    """
    Class docstring: Brief description of the NotificationConsumer class.
    """

    dependencies = [
        ('blog_api', '0011_alter_post_last_visit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='last_visit',
        ),
    ]
