# Generated by Django 4.2.11 on 2024-03-14 07:52
"""
Class docstring: Brief description of the NotificationConsumer class.
"""
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    """
    Class docstring: Brief description of the NotificationConsumer class.
    """

    dependencies = [
        ('blog_api', '0014_remove_post_last_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='to_be_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
