# Generated by Django 4.2.11 on 2024-03-14 08:08
"""
Class docstring: Brief description of the NotificationConsumer class.
"""
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Class docstring: Brief description of the NotificationConsumer class.
    """

    dependencies = [
        ('blog_api', '0015_post_to_be_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='to_be_posted',
            field=models.DateTimeField(
                default='2024-03-16 10:15:30.123456+00:00'),
        ),
    ]
