# Generated by Django 4.2.11 on 2024-03-15 05:02
"""
Class docstring: Brief description of the NotificationConsumer class.
"""
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Class docstring: Brief description of the NotificationConsumer class.
    """

    dependencies = [
        ('blog_api', '0016_alter_post_to_be_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_post_pro',
            field=models.BooleanField(default=False),
        ),
    ]
