# Generated by Django 4.2.11 on 2024-05-07 11:17
"""
Class docstring: Brief description of the NotificationConsumer class.
"""
from django.db import migrations, models

import blog_api.models


class Migration(migrations.Migration):
    """
    Class docstring: Brief description of the NotificationConsumer class.
    """

    dependencies = [
        ('blog_api', '0020_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='posts/default.jpg', upload_to=blog_api.models.upload_to, verbose_name='Image'),
        ),
    ]
