# Generated by Django 4.2.11 on 2024-05-30 08:59

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0026_fileuploader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileuploader',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/media/posts/csvfiles/'), upload_to=''),
        ),
    ]
