# Generated by Django 4.2.11 on 2024-05-30 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0027_alter_fileuploader_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileuploader',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
