# Generated by Django 4.2.11 on 2024-06-05 06:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog_api', '0029_like_action_alter_fileuploader_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notif_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
