# Generated by Django 4.2.11 on 2024-06-06 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0031_useraddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='zip_code',
            field=models.IntegerField(),
        ),
    ]
