# Generated by Django 4.2.11 on 2024-06-07 06:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0032_alter_useraddress_zip_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colour', models.CharField(choices=[('black', 'Black'), ('blue', 'Blue'), ('white', 'White'), ('brown', 'Brown')], default=None, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProductTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sizes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('x', 'X'), ('m', 'M'), ('l', 'L'), ('xl', 'XL'), ('xxl', 'XXL')], default=None, max_length=20)),
                ('stock', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='useraddress',
            name='order_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='post',
            name='to_be_posted',
            field=models.DateTimeField(),
        ),
        migrations.CreateModel(
            name='Variation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colour', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('size', models.ManyToManyField(to='blog_api.sizes')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('price', models.FloatField()),
                ('discount', models.FloatField()),
                ('offerEnd', models.DateField(default=django.utils.timezone.now)),
                ('new', models.BooleanField(default=False)),
                ('rating', models.FloatField()),
                ('saleCount', models.FloatField(max_length=20)),
                ('shortdescription', models.TextField(max_length=300)),
                ('longdescription', models.TextField(max_length=1000)),
                ('image', models.ImageField(upload_to='')),
                ('category', models.ManyToManyField(to='blog_api.productcategory')),
                ('tag', models.ManyToManyField(to='blog_api.producttags')),
            ],
        ),
        migrations.AddField(
            model_name='useraddress',
            name='products_chosen',
            field=models.ManyToManyField(to='blog_api.products'),
        ),
    ]
