# Generated by Django 4.2.11 on 2024-06-07 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0033_colours_productcategory_producttags_sizes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraddress',
            name='order_price',
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='products_chosen',
        ),
        migrations.AlterField(
            model_name='products',
            name='discount',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='products',
            name='rating',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='saleCount',
            field=models.PositiveIntegerField(),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_price', models.FloatField(default=0.0)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_api.useraddress')),
                ('products_chosen', models.ManyToManyField(to='blog_api.products')),
            ],
        ),
    ]
