# Generated by Django 4.2.11 on 2024-06-07 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0034_remove_useraddress_order_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colours',
            name='colour',
            field=models.CharField(default='Black', max_length=20),
        ),
        migrations.AlterField(
            model_name='variation',
            name='colour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_api.colours'),
        ),
    ]
