# Generated by Django 4.2.11 on 2024-06-07 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0035_alter_colours_colour_alter_variation_colour'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='variations',
            field=models.ManyToManyField(to='blog_api.variation'),
        ),
    ]
