# Generated by Django 4.2.11 on 2024-06-12 08:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0037_alter_products_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='to_be_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
