# Generated by Django 4.2.11 on 2024-06-12 08:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0038_alter_post_to_be_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='to_be_posted',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
