# Generated by Django 4.2.11 on 2024-06-12 11:12

import blog_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0040_alter_post_to_be_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(default='posts/default.jpg', upload_to=blog_api.models.upload_to, verbose_name='Thumbnail'),
        ),
    ]
