# Generated by Django 4.2.11 on 2024-06-24 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0041_alter_post_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileuploader',
            old_name='file',
            new_name='csv_file',
        ),
    ]
