# Generated by Django 4.2.11 on 2024-06-24 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0042_rename_file_fileuploader_csv_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecommerce',
            name='product_color',
            field=models.CharField(default='red', max_length=100),
        ),
        migrations.AddField(
            model_name='ecommerce',
            name='product_description',
            field=models.CharField(default='red', max_length=100),
        ),
        migrations.AddField(
            model_name='ecommerce',
            name='product_weight',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='ecommerce',
            name='iban',
            field=models.CharField(default='red', max_length=200),
        ),
        migrations.AlterField(
            model_name='ecommerce',
            name='product_brand',
            field=models.CharField(default='red', max_length=200),
        ),
        migrations.AlterField(
            model_name='ecommerce',
            name='product_category',
            field=models.CharField(default='red', max_length=200),
        ),
        migrations.AlterField(
            model_name='ecommerce',
            name='product_name',
            field=models.CharField(default='red', max_length=100),
        ),
        migrations.AlterField(
            model_name='ecommerce',
            name='product_price',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='ecommerce',
            name='product_rating',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='ecommerce',
            name='quantity_in_stock',
            field=models.IntegerField(default=1),
        ),
    ]
