# Generated by Django 4.0.3 on 2024-03-11 09:40
"""
Connect method docstring: Brief description of the connect method.
"""
from django.db import migrations, models


class Migration(migrations.Migration):
    """
Connect method docstring: Brief description of the connect method.
"""

    dependencies = [
        ('users', '0004_alter_user_options_rename_user_name_user_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
    ]
