# Generated by Django 4.2.11 on 2024-03-15 05:02
"""
Connect method docstring: Brief description of the connect method.
"""
from django.db import migrations, models


class Migration(migrations.Migration):
    """
Connect method docstring: Brief description of the connect method.
"""

    dependencies = [
        ('users', '0006_alter_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_payment_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_pro',
            field=models.BooleanField(default=False),
        ),
    ]
