# Generated by Django 4.2.11 on 2024-03-14 11:15
"""
    Connect method docstring: Brief description of the connect method.
    """
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Connect method docstring: Brief description of the connect method.
    """
    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsLetterUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, 
                                           primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
