# Generated by Django 4.2.11 on 2024-03-14 11:33
"""
    Connect method docstring: Brief description of the connect method.
    """
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Connect method docstring: Brief description of the connect method.
    """
    dependencies = [
        ('contact', '0002_newsletterusers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletterusers',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
