# Generated by Django 4.2.11 on 2024-03-28 07:54
"""
    Connect method docstring: Brief description of the connect method.
    """
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Connect method docstring: Brief description of the connect method.
    """
    dependencies = [
        ('contact', '0003_alter_newsletterusers_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='name',
            field=models.CharField(default='name', max_length=100),
        ),
    ]
